name: Deploy Personal-Cookbook
run-name: ${{ github.event.head_commit.message }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
    - master
jobs:
  Despliegue-Front:
    runs-on: ubuntu-latest
    environment: master 
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
      COGNITO_POOL_ID: ${{ secrets.COGNITO_POOL_ID }}
      VUE_APP_HOST: ${{ secrets.VUE_APP_HOST }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.1
      - name: setting up node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
      - name: Create .env with Github Secrets
        working-directory: ./frontend
        run: |
          touch .env
          echo VUE_APP_COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID >> .env
          
          echo VUE_APP_COGNITO_POOL_ID=$COGNITO_POOL_ID >> .env
          echo VUE_APP_HOST=$VUE_APP_HOST >> .env
      - name: NPM install
        run: npm install
        working-directory: ./frontend
      - name: NPM Build
        run: npm run build
        working-directory: ./frontend
      - name: Upload S3
      
        uses: reggionick/s3-deploy@v4
        with:
          folder: frontend/dist
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: eu-central-1
  Deploy-EC2:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: master 
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{ secrets.VUE_APP_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@${HOSTNAME} '
              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ec2-user/personal-cookbook &&
              git checkout master &&
              git fetch --all &&
              git reset --hard origin/master &&
              git pull origin master &&
              pm2 restart all
              '
